// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:333544961571:web:4e6fa45e3933461269e396',
    messagingSenderId: '333544961571',
    projectId: 'dentshade-d66e1',
    authDomain: 'dentshade-d66e1.firebaseapp.com',
    storageBucket: 'dentshade-d66e1.firebasestorage.app',
    measurementId: 'G-R961Q2V751',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:333544961571:android:cc72640322af0f34530f41',
    messagingSenderId: '333544961571',
    projectId: 'dentshade-d66e1',
    storageBucket: 'dentshade-d66e1.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:333544961571:ios:e78b23b67dad938e530f41',
    messagingSenderId: '333544961571',
    projectId: 'dentshade-d66e1',
    storageBucket: 'dentshade-d66e1.firebasestorage.app',
    iosBundleId: 'com.example.dentcare',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:333544961571:ios:e78b23b67dad938e530f41',
    messagingSenderId: '333544961571',
    projectId: 'dentshade-d66e1',
    storageBucket: 'dentshade-d66e1.firebasestorage.app',
    iosBundleId: 'com.example.dentcare',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? '',
    appId: '1:333544961571:web:49a3616a864a1368530f41',
    messagingSenderId: '333544961571',
    projectId: 'dentshade-d66e1',
    authDomain: 'dentshade-d66e1.firebaseapp.com',
    storageBucket: 'dentshade-d66e1.firebasestorage.app',
  );
}
